# Generated by Plain 0.21.4 on 2025-02-11 18:03

import plain.passwords.models
import plain.passwords.validators
import plain.postgres.functions.text
from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("email", postgres.EmailField(max_length=254)),
                (
                    "password",
                    plain.passwords.models.PasswordField(
                        validators=[
                            plain.passwords.validators.MinimumLengthValidator(),
                            plain.passwords.validators.CommonPasswordValidator(),
                            plain.passwords.validators.NumericPasswordValidator(),
                        ]
                    ),
                ),
                ("is_admin", postgres.BooleanField(default=False)),
                ("created_at", postgres.DateTimeField(create_now=True)),
            ],
            options={
                "constraints": [
                    postgres.UniqueConstraint(
                        plain.postgres.functions.text.Lower("email"),
                        name="unique_lower_email",
                    ),
                ],
            },
        ),
    ]
