# Generated by Bolt 5.0.dev20240612160253 on 2024-06-12 21:17

import bolt.passwords.models
import bolt.passwords.validators
from bolt.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "password",
                    bolt.passwords.models.PasswordField(
                        validators=[
                            bolt.passwords.validators.MinimumLengthValidator(),
                            bolt.passwords.validators.CommonPasswordValidator(),
                            bolt.passwords.validators.NumericPasswordValidator(),
                        ]
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
