# Generated by Plain 0.97.0 on 2026-01-13 16:53

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="time_zone",
            field=postgres.TimeZoneField(allow_null=True, required=False),
        ),
    ]
