# Generated by Plain 0.97.0 on 2026-01-13 16:53

from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="time_zone",
            field=models.TimeZoneField(allow_null=True, max_length=100, required=False),
        ),
    ]
