# Generated by Plain 0.132.1 on 2026-04-14 21:31

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_time_zone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=postgres.EmailField(),
        ),
    ]
